name = "QuantumControl"
uuid = "8a270532-f23f-47a8-83a9-b33d10cad486"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.9.1+dev"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"

[extensions]
QuantumControlZygoteExt = "Zygote"
QuantumControlFiniteDifferencesExt = "FiniteDifferences"

[compat]
FileIO = "1"
FiniteDifferences = "0.12"
IOCapture = "0.2.4"
JLD2 = "0.4"
QuantumControlBase = ">=0.9.3"
QuantumPropagators = ">=0.7.5"
Zygote = "0.6"
julia = "1.9"
