name: CI
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '*'
  pull_request:
    branches:
      - master
env:
  GKSwstype: 100
  JULIA_PKG_PRECOMPILE_AUTO: false
jobs:
  test:
    name: Test ${{ matrix.title }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: 'Linux - Latest'
            os: ubuntu-latest
            version: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - name: "Instantiate test environment"
        run: |
          wget https://raw.githubusercontent.com/JuliaQuantumControl/JuliaQuantumControl/master/scripts/installorg.jl
          julia --project=test installorg.jl
      - name: "Run tests"
        shell: julia --color=yes --project=test --code-coverage="@" --depwarn="yes" --check-bounds="yes" {0}
        run: |
          include(joinpath(pwd(), "test", "runtests.jl"))
      - name: "Run downstream Krotov tests"
        shell: julia --color=yes --project=test --code-coverage="@" --depwarn="yes" --check-bounds="yes" {0}
        run: |
          import Krotov
          include(pkgdir(Krotov, "test", "runtests.jl"))
      - name: "Run downstream GRAPE tests"
        shell: julia --color=yes --project=test --code-coverage="@" --depwarn="yes" --check-bounds="yes" {0}
        run: |
          import GRAPE
          include(pkgdir(GRAPE, "test", "runtests.jl"))
      - name: "Summarize coverage"
        shell: julia --project=test {0}
        run: |
          using QuantumControlTestUtils
          show_coverage()
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          # Install Python dependencies
          set -x
          /usr/bin/python3 -m pip install zip-files
      - name: "Instantiate test environment"
        run: |
          # Instantiate Pkg
          wget https://raw.githubusercontent.com/JuliaQuantumControl/JuliaQuantumControl/master/scripts/installorg.jl
          install -m 600 -D /dev/null ~/.ssh/known_hosts
          ssh-keyscan -H github.com > ~/.ssh/known_hosts
          julia --project=test -e 'include("installorg.jl"); installorg(; github="develop")'
          # installing in develop mode enables proper "source" links in subpackage APIs
      - name: "Build documentation"
        run: julia --project=test docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - name: Zip the HTML documentation
        run: zip-folder --debug --auto-root --outfile "docs.zip" docs/build
      - uses: actions/upload-artifact@v3
        name: Upload documentation artifacts
        with:
          name: QuantumControl
          # We need at least two files in the artifact to avoid a weird
          # double-zip file. Hence README.md
          path: |
            README.md
            ./docs.zip
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Get codestyle settings
        run: wget https://raw.githubusercontent.com/JuliaQuantumControl/JuliaQuantumControl/master/.JuliaFormatter.toml
      - name: Install JuliaFormatter and format
        shell: julia {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="JuliaFormatter"))
          using JuliaFormatter
          format(".", verbose=true)
      - name: Format Check
        shell: julia {0}
        run: |
          out = Cmd(`git diff -U0`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!\n\n$out"
              exit(1)
          end
